config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products, only: [:index, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  # TODO Need to add some validations here
end

# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  original_id :integer
#  name        :string
#  price       :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  url         :text
#

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  scope :filter, ->(term) { where('text LIKE ?', "%#{term}%") if term }

  # TODO Need to add some validations here
end

# == Schema Information
#
# Table name: reviews
#
#  id         :integer          not null, primary key
#  product_id :integer
#  title      :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews.filter(params[:term])
  end

  def create
    result = WalmartParser.call(url: params[:url])

    if result.success?
      redirect_to result.product
    else
      # we can get error here and display it #{result.error}
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SDTest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/products/_form.html.slim
= form_tag(products_path, method: :post) do
  .field
    = text_field_tag :url

  .actions
    = submit_tag 'Parse!', name: nil

app/views/products/_info.html.slim
div Name: #{@product.name}
div Price: #{@product.price}
div Url: #{link_to(@product.url, @product.url)}

app/views/products/_list.html.slim
- @products.each do |product|
  div = link_to(product.name, product)

app/views/products/_reviews.html.slim
= form_tag(product_path(@product), method: :get) do
  = text_field_tag :term, params[:term]
  = submit_tag 'Filter', name: nil

- @reviews.each do |review|
  .reviews-list
    p
      b = review.title

    p = review.text

app/views/products/index.html.slim
h1 Fetch product information
= render 'form'

h1 List of parsed products
= render 'list'

app/views/products/show.html.slim
= link_to 'Back', products_path

h2 Product information:
= render 'info'

h2 Reviews:
= render 'reviews'